{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e8b26cd7-1a7f-402a-8048-4d2e38303e0b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "DataFrame has been saved to 'aromatics_data.csv'\n"
     ]
    }
   ],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.common.by import By\n",
    "import time\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd\n",
    "\n",
    "def is_number(variable):\n",
    "    dot_count = 0\n",
    "    for char in variable:\n",
    "        if not char.isdigit() and char != '.':\n",
    "            return False\n",
    "        if char == '.':\n",
    "            dot_count += 1\n",
    "            if dot_count > 1:\n",
    "                return False\n",
    "    return True\n",
    "    \n",
    "# Initialize empty lists to store data\n",
    "all_product_urls = []\n",
    "all_product_titles = []\n",
    "all_countries = []\n",
    "all_cultivations = []\n",
    "all_botanical_families = []\n",
    "all_plant_parts = []\n",
    "all_chemical_families = []\n",
    "all_extraction_methods = []\n",
    "all_therapeutic_properties = []\n",
    "all_aromas = []\n",
    "all_notes = []\n",
    "all_suggested_uses = []\n",
    "all_sorted_sections = []\n",
    "\n",
    "# Initialize Selenium WebDriver\n",
    "driver = webdriver.Chrome()\n",
    "\n",
    "# Loop through each page\n",
    "for page_num in range(1, 11):\n",
    "    # URL of the current page\n",
    "    url = f'https://www.aromatics.com/collections/essential-oil-singles?page={page_num}'\n",
    "\n",
    "    # Fetch the HTML content of the webpage\n",
    "    response = requests.get(url)\n",
    "    html_content = response.text\n",
    "\n",
    "    # Parse the HTML content using BeautifulSoup\n",
    "    soup = BeautifulSoup(html_content, 'html.parser')\n",
    "\n",
    "    # Find all the <a> elements containing product information\n",
    "    product_links = soup.find_all('a', class_='product-name')\n",
    "\n",
    "    # Extract product details from each product page\n",
    "    for link in product_links:\n",
    "        # Extract product URL\n",
    "        product_url = 'https://www.aromatics.com' + link['href']\n",
    "        driver.get(product_url)\n",
    "        # Wait for the dynamic content to load (you may need to adjust the wait time as needed)\n",
    "        time.sleep(10)\n",
    "        product_html_content = driver.page_source\n",
    "        product_soup = BeautifulSoup(product_html_content, 'html.parser')\n",
    "        \n",
    "        # Extract product title\n",
    "        product_title_div = product_soup.find('div', class_='product__title')\n",
    "        product_title_tag = product_title_div.find('h1', class_='h2 m-0')\n",
    "        product_title = product_title_tag.text.strip() if product_title_tag else \"Product title not found\"\n",
    "\n",
    "        # Extract product properties\n",
    "        product_properties_div = product_soup.find_all('div', class_='product-properties flex grid grid--3-col-tablet grid--3-col-desktop grid--3-col')\n",
    "        # Definning properties to be extracted\n",
    "        properties = [\"Country\", \"Cultivation\", \"Botanical Families\", \"Plant Part\", \"Chemical Families\", \"Extraction Method\"]\n",
    "\n",
    "        # Initialize variables to store the extracted values\n",
    "        country = cultivation = botanical_families = plant_part = chemical_families = extraction_method = []\n",
    "\n",
    "        # Find all items with class 'product-properties__item'\n",
    "        items = product_properties_div[0].find_all(class_=\"product-properties__item\")\n",
    "\n",
    "        # Loop through each item\n",
    "        for item in items:\n",
    "            # Find the title and content elements\n",
    "            title_element = item.find(class_=\"product-properties__title\")\n",
    "            content_elements = item.find_all(class_=\"product-properties__content\")\n",
    "    \n",
    "            # Extract the text from title and content elements\n",
    "            title = title_element.get_text(strip=True)\n",
    "            content = content_elements[0].get_text(strip=True) if content_elements else \"\"\n",
    "    \n",
    "            # Check if the title is in the properties list and assign the content to the corresponding variable\n",
    "            if title == \"Country\":\n",
    "                country = content\n",
    "            elif title == \"Cultivation\":\n",
    "                cultivation = content\n",
    "            elif title == \"Botanical Families\":\n",
    "                botanical_families = content\n",
    "            elif title == \"Plant Part\":\n",
    "                plant_part = content\n",
    "            elif title == \"Chemical Families\":\n",
    "                chemical_families.extend([content.get_text(strip=True) for content in content_elements])\n",
    "            elif title == \"Extraction Method\":\n",
    "                extraction_method = content \n",
    "\n",
    "        # Extract therapeutic & aromatic properties\n",
    "        product_therapeutic_div = product_properties_div[1]\n",
    "        \n",
    "        # Definning properties to be extracted\n",
    "        properties_therapeutic=[\"Therapeutic Properties\",\"Notes\",\"Aromas\"]\n",
    "        \n",
    "        # Initialize variables to store the extracted values\n",
    "        therapeutic_properties = []\n",
    "        notes = []\n",
    "        aromas = []\n",
    "        \n",
    "        # Find all items with class 'product-properties__item'\n",
    "        therapeutic_items = product_therapeutic_div.find_all(class_=\"product-properties__item\")\n",
    "\n",
    "        # Loop through each item\n",
    "        for item in therapeutic_items:\n",
    "            \n",
    "            # Find the title and content elements\n",
    "            title_element = item.find(class_=\"product-properties__title\")\n",
    "            content_elements = item.find_all(class_=\"product-properties__content\")\n",
    "            \n",
    "            # Extract the text from title and content elements\n",
    "            if title_element:\n",
    "               title = title_element.get_text(strip=True)\n",
    "            \n",
    "\n",
    "            # Check if the title is in the properties list and assign the content to the corresponding variable\n",
    "            if title == \"Therapeutic Properties\":\n",
    "                for content in content_elements:\n",
    "                  therapeutic_properties.append(content.get_text(strip=True))\n",
    "            elif title == \"Notes\":\n",
    "                for content1 in content_elements:\n",
    "                  notes.append(content1.get_text(strip=True))\n",
    "            elif title == \"Aromas\":\n",
    "                for content2 in content_elements:\n",
    "                  aromas.append(content2.get_text(strip=True))\n",
    "                \n",
    "        # Extract suggested uses\n",
    "        suggested_uses_div = product_soup.find_all('div', class_='accordion__content body-big rte')\n",
    "\n",
    "        # Initialize variables to store the extracted values\n",
    "        suggested_uses = []\n",
    "\n",
    "        # Find all items with 'strong' tags\n",
    "        suggested_items = suggested_uses_div[2].find_all('strong')\n",
    "\n",
    "        # Loop through each item\n",
    "        for item in suggested_items:\n",
    "            suggested_uses.append(item.get_text(strip=True))\n",
    "\n",
    "        # Extract GCMS Data\n",
    "        gcms_div = product_soup.find('div', class_='gcms-data__container')\n",
    "        if gcms_div:\n",
    "            link = gcms_div.find('a')\n",
    "            gcms_href ='https://www.aromatics.com' + link['href']\n",
    "            driver.get(gcms_href)\n",
    "            time.sleep(5)\n",
    "            \n",
    "            # Pressing compare batches\n",
    "            div_element = driver.find_element(By.CSS_SELECTOR, 'div.inline-block.align-top')\n",
    "            div_element.click()\n",
    "            time.sleep(5)\n",
    "\n",
    "            #extract data using Selenium from table body\n",
    "            gcms_table = driver.find_elements(By.TAG_NAME, \"tbody\")\n",
    "            gcms_table_text = [element.text for element in gcms_table]\n",
    "\n",
    "            # Initialize a dictionary to store the sorted sections\n",
    "            sorted_sections = {}\n",
    "\n",
    "            # Iterate over each section in the list\n",
    "            for section in gcms_table_text:\n",
    "                # Split the section into lines\n",
    "                lines = section.split('\\n')\n",
    "                # Extract the section name\n",
    "                section_name = lines[0]\n",
    "                # Split the section into assets\n",
    "                assets = lines[1:]\n",
    "                # Initialize a list to store sorted assets\n",
    "                sorted_assets = []\n",
    "                # Iterate over each asset in the section\n",
    "                i = 0\n",
    "                while i < len(assets):\n",
    "                    # Extract asset name\n",
    "                    asset_name = assets[i]\n",
    "                    # Extract numeric values\n",
    "                    numeric_values = []\n",
    "                    i += 1  # Move to the next line for numeric values\n",
    "                    while i < len(assets) :  # Check if the line starts with a dash\n",
    "                        if assets[i] == '-':\n",
    "                            numeric_values.append(0)\n",
    "                        elif is_number(assets[i].rstrip('%')):\n",
    "                            numeric_values.append(float(assets[i].rstrip('%')))\n",
    "                        else:\n",
    "                            break\n",
    "                        i += 1\n",
    "                    # Create a tuple containing asset name and numeric values\n",
    "                    asset_tuple = (asset_name, numeric_values)\n",
    "                    # Append the asset tuple to the list of sorted assets\n",
    "                    sorted_assets.append(asset_tuple)\n",
    "                # Store the sorted assets in the dictionary\n",
    "                sorted_sections[section_name] = sorted_assets\n",
    "\n",
    "            \n",
    "\n",
    "        # Append data to respective lists\n",
    "        all_product_urls.append(product_url)\n",
    "        all_product_titles.append(product_title)\n",
    "        all_countries.append(country)\n",
    "        all_cultivations.append(cultivation)\n",
    "        all_botanical_families.append(botanical_families)\n",
    "        all_plant_parts.append(plant_part)\n",
    "        all_chemical_families.append(chemical_families)\n",
    "        all_extraction_methods.append(extraction_method)\n",
    "        all_therapeutic_properties.append(therapeutic_properties)\n",
    "        all_aromas.append(aromas)\n",
    "        all_notes.append(notes)\n",
    "        all_suggested_uses.append(suggested_uses)\n",
    "        all_sorted_sections.append(sorted_sections)\n",
    "      \n",
    "\n",
    "# Create a DataFrame from the extracted data\n",
    "df = pd.DataFrame({\n",
    "    'Product URL': all_product_urls,\n",
    "    'Product Title': all_product_titles,\n",
    "    'Country': all_countries,\n",
    "    'Cultivation': all_cultivations,\n",
    "    'Botanical Families': all_botanical_families,\n",
    "    'Plant Part': all_plant_parts,\n",
    "    'Chemical Families': all_chemical_families,\n",
    "    'Extraction Method': all_extraction_methods,\n",
    "    'Therapeutic & Aromatic Properties': all_therapeutic_properties,\n",
    "    'Notes': all_notes,\n",
    "    'Aroma': all_aromas,\n",
    "    'Suggested uses': all_suggested_uses,\n",
    "    'GCMS analysis': all_sorted_sections\n",
    "    })\n",
    "\n",
    "# Close the WebDriver\n",
    "driver.quit()\n",
    "\n",
    "# Specify the file path where csv file saved\n",
    "file_path = 'aromatics_data.csv'\n",
    "\n",
    "# Save the DataFrame to a CSV file\n",
    "df.to_csv(file_path, index=False)\n",
    "\n",
    "# Print a message to confirm that the file has been saved\n",
    "print(f\"DataFrame has been saved to '{file_path}'\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "709a2350-9aa1-4087-b782-dce0024c7c62",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
